In [4]:
from __future__ import division, print_function, absolute_import
from past.builtins import basestring

import os

import pandas as pd

from twip.constant import DATA_PATH

In [2]:
import matplotlib
from IPython.display import display, HTML 
%matplotlib inline
np = pd.np
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_rows', 6)
pd.set_option('display.max_columns', 250)

In [3]:
df = pd.read_csv(os.path.join(DATA_PATH, 'cleaned_tweets.csv.gz'), low_memory=False)

In [5]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [7]:
df.get_
df.get_dtype_counts()

bool        15
float64     51
int64       12
object     209
dtype: int64

In [15]:
dtypes = pd.Series([df[v].dtype for v in df.columns], index=df.columns)
dtypes

Unnamed: 0                   int64
id                           int64
coordinates_coordinates     object
                            ...
user_url                    object
user_utc_offset            float64
user_verified                 bool
dtype: object

In [31]:
mask = [col for col in df.columns if df[col].dtype in (bool, float, np.dtype('int64'))]  # don't forget bool and int64 (not int)!
mask
numbers = df[mask]
numbers

,Unnamed: 0,id,favorite_count,favorited,id_str,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,is_quote_status,lat,lon,quoted_status_favorite_count,quoted_status_id,quoted_status_id_str,quoted_status_retweet_count,quoted_status_user_favourites_count,quoted_status_user_followers_count,quoted_status_user_friends_count,quoted_status_user_id,quoted_status_user_id_str,quoted_status_user_listed_count,quoted_status_user_statuses_count,quoted_status_user_utc_offset,quoted_status_id.1,quoted_status_id_str.1,retweet_count,retweeted,retweeted_status_favorite_count,retweeted_status_id,retweeted_status_id_str,retweeted_status_in_reply_to_status_id,retweeted_status_in_reply_to_status_id_str,retweeted_status_in_reply_to_user_id,retweeted_status_in_reply_to_user_id_str,retweeted_status_quoted_status_favorite_count,retweeted_status_quoted_status_id,retweeted_status_quoted_status_id_str,retweeted_status_quoted_status_retweet_count,retweeted_status_quoted_status_user_favourites_count,retweeted_status_quoted_status_user_followers_count,retweeted_status_quoted_status_user_friends_count,retweeted_status_quoted_status_user_id,retweeted_status_quoted_status_user_id_str,retweeted_status_quoted_status_user_listed_count,retweeted_status_quoted_status_user_statuses_count,retweeted_status_quoted_status_user_utc_offset,retweeted_status_quoted_status_id.1,retweeted_status_quoted_status_id_str.1,retweeted_status_retweet_count,retweeted_status_user_favourites_count,retweeted_status_user_followers_count,retweeted_status_user_friends_count,retweeted_status_user_id,retweeted_status_user_id_str,retweeted_status_user_listed_count,retweeted_status_user_statuses_count,retweeted_status_user_utc_offset,truncated,user_contributors_enabled,user_default_profile,user_default_profile_image,user_favourites_count,user_followers_count,user_friends_count,user_geo_enabled,user_has_extended_profile,user_id,user_id_str,user_is_translation_enabled,user_is_translator,user_listed_count,user_profile_background_tile,user_profile_use_background_image,user_protected,user_statuses_count,user_utc_offset,user_verified
0,0,731122251278499841,0,False,731122251278499841,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,False,19.0,7.311145e+17,7.311145e+17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,0.0,90268.0,130.0,150820027.0,150820027.0,1717.0,37567.0,10800.0,False,False,False,False,845,221,709,False,False,65061698,65061698,False,False,8,False,False,False,579,-14400.0,False
1,1,724281574129180672,0,False,724281574129180672,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,False,0,776,1910,True,False,3110463964,3110463964,False,False,4,False,True,False,2159,-25200.0,False
2,2,724281535587856384,0,False,724281535587856384,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,105,2615,591,False,False,1258138550,1258138550,True,False,966,True,True,False,14193,3600.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193375,193375,724275609858392066,0,False,724275609858392066,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,False,10.0,7.242686e+17,7.242686e+17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,23339.0,5678.0,39.0,745911914.0,745911914.0,682.0,11640.0,-10800.0,False,False,True,False,161,867,2,False,False,3428977365,3428977365,False,False,1514,False,True,False,10422,NaN,False
193376,193376,724275578879111169,0,False,724275578879111169,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,105,819,275,True,False,385181009,385181009,False,False,1,True,True,False,59510,25200.0,False
193377,193377,724275568871673857,0,False,724275568871673857,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,1,61,15,False,False,302987528,302987528,False,False,4,False,True,False,124,28800.0,False

In [32]:
numbers.to_csv(os.path.join(DATA_PATH, 'numbers.csv.gz'), compression='gzip')