In [3]:
from __future__ import division, print_function, absolute_import
from past.builtins import basestring

import os

import pandas as pd

from twip.constant import DATA_PATH

In [4]:
import matplotlib
from IPython.display import display, HTML 
%matplotlib inline
np = pd.np
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_rows', 6)
pd.set_option('display.max_columns', 250)

In [5]:
df = pd.read_csv(os.path.join(DATA_PATH, 'cleaned_tweets.csv.gz'), low_memory=False)
rawlen = len(df)
df.drop_duplicates('id_str', keep='last', inplace=True)
rawlen - len(df)

10308

In [6]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [8]:
# df.get_
df.get_dtype_counts()

bool        15
float64     51
int64       12
object     209
dtype: int64

In [9]:
dtypes = pd.Series([df[v].dtype for v in df.columns], index=df.columns)
dtypes

Unnamed: 0                   int64
id                           int64
coordinates_coordinates     object
                            ...
user_url                    object
user_utc_offset            float64
user_verified                 bool
dtype: object

In [10]:
mask = [col for col in df.columns if df[col].dtype in (bool, float, np.dtype('int64'))]  # don't forget bool and int64 (not int)!
mask
numbers = df[mask]
numbers

,Unnamed: 0,id,favorite_count,favorited,id_str,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,is_quote_status,lat,lon,quoted_status_favorite_count,quoted_status_id,quoted_status_id_str,quoted_status_retweet_count,quoted_status_user_favourites_count,quoted_status_user_followers_count,quoted_status_user_friends_count,quoted_status_user_id,quoted_status_user_id_str,quoted_status_user_listed_count,quoted_status_user_statuses_count,quoted_status_user_utc_offset,quoted_status_id.1,quoted_status_id_str.1,retweet_count,retweeted,retweeted_status_favorite_count,retweeted_status_id,retweeted_status_id_str,retweeted_status_in_reply_to_status_id,retweeted_status_in_reply_to_status_id_str,retweeted_status_in_reply_to_user_id,retweeted_status_in_reply_to_user_id_str,retweeted_status_quoted_status_favorite_count,retweeted_status_quoted_status_id,retweeted_status_quoted_status_id_str,retweeted_status_quoted_status_retweet_count,retweeted_status_quoted_status_user_favourites_count,retweeted_status_quoted_status_user_followers_count,retweeted_status_quoted_status_user_friends_count,retweeted_status_quoted_status_user_id,retweeted_status_quoted_status_user_id_str,retweeted_status_quoted_status_user_listed_count,retweeted_status_quoted_status_user_statuses_count,retweeted_status_quoted_status_user_utc_offset,retweeted_status_quoted_status_id.1,retweeted_status_quoted_status_id_str.1,retweeted_status_retweet_count,retweeted_status_user_favourites_count,retweeted_status_user_followers_count,retweeted_status_user_friends_count,retweeted_status_user_id,retweeted_status_user_id_str,retweeted_status_user_listed_count,retweeted_status_user_statuses_count,retweeted_status_user_utc_offset,truncated,user_contributors_enabled,user_default_profile,user_default_profile_image,user_favourites_count,user_followers_count,user_friends_count,user_geo_enabled,user_has_extended_profile,user_id,user_id_str,user_is_translation_enabled,user_is_translator,user_listed_count,user_profile_background_tile,user_profile_use_background_image,user_protected,user_statuses_count,user_utc_offset,user_verified
87,87,724276510626979840,0,False,724276510626979840,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,False,0,1,12,False,True,2957565833,2957565833,False,False,3,False,True,False,182,NaN,False
88,88,724276498249572352,0,False,724276498249572352,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,56,454,197,True,False,86312900,86312900,False,False,5,True,True,False,117794,25200.0,False
90,90,724276388325412866,1,False,724276388325412866,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,12475,3110,4998,False,False,1391270923,1391270923,False,False,60,False,True,False,23206,-14400.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193375,193375,724275609858392066,0,False,724275609858392066,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,False,10.0,7.242686e+17,7.242686e+17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,23339.0,5678.0,39.0,745911914.0,745911914.0,682.0,11640.0,-10800.0,False,False,True,False,161,867,2,False,False,3428977365,3428977365,False,False,1514,False,True,False,10422,NaN,False
193376,193376,724275578879111169,0,False,724275578879111169,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,105,819,275,True,False,385181009,385181009,False,False,1,True,True,False,59510,25200.0,False
193377,193377,724275568871673857,0,False,724275568871673857,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,False,1,61,15,False,False,302987528,302987528,False,False,4,False,True,False,124,28800.0,False

In [11]:
numbers.to_csv(os.path.join(DATA_PATH, 'numbers.csv.gz'), compression='gzip')